name: 'init mac on github'
description: 'initialize mac on github'

runs:
  using: "composite"
  steps:
    - name: disbale unused services
      run: |
        launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
        sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist
      shell: bash
